This lead to Dependabot error
updater | ERROR <job_540962562> undefined method `name' for nil:NilClass
updater | <job_540962562>
updater | <job_540962562>           return @properties[buildfile.name] if @properties[buildfile.name]
updater | <job_540962562>                                                                      ^^^^^
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb:110:in `properties'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb:91:in `block in property_details'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb:90:in `each'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb:90:in `property_details'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser/property_value_finder.rb:98:in `property_value'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:266:in `evaluated_value'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:194:in `dependency_from'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:168:in `block (2 levels) in plugin_dependencies'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:160:in `each'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:160:in `block in plugin_dependencies'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:159:in `each'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:159:in `plugin_dependencies'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:75:in `buildfile_dependencies'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:42:in `block in parse'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:41:in `each'
updater | ERROR <job_540962562> /home/dependabot/gradle/lib/dependabot/gradle/file_parser.rb:41:in `parse'
updater | ERROR <job_540962562> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:609:in `dependencies'
updater | ERROR <job_540962562> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_540962562> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_540962562> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_540962562> bin/update_files.rb:23:in `<main>'

This reverts commit 01c697b730516e038492144d093c25143bd41a57.